Rookout/microservices-demo

README.md
skaffold.yaml
src/cartservice/src/cartstore/RedisCartStore.cs

setup and document development environmet

RK-9695 - Setup dev env

---

README.md
src/emailservice/email_server.py
src/emailservice/requirements.txt

trying to add openTracing instead of openCensus to emailservice.
we're going to deploy and see if it works.

RK-9700 - Open tracing

---

Makefile
src/adservice/Dockerfile
src/cartservice/src/Dockerfile
src/checkoutservice/Dockerfile
src/currencyservice/Dockerfile
src/emailservice/Dockerfile
src/frontend/Dockerfile
src/loadgenerator/Dockerfile
src/paymentservice/Dockerfile
src/productcatalogservice/Dockerfile
src/recommendationservice/Dockerfile
src/shippingservice/Dockerfile

Add commit and remote origin info to docker images.

RK-9801 - add rookout commit and origin to docker images

---

src/checkoutservice/Dockerfile
src/frontend/Dockerfile
src/productcatalogservice/Dockerfile
src/shippingservice/Dockerfile

RK-10874 - bump gorook to 0.0.5

---

src/adservice/build.gradle

upgrading log4j to mitigate log4shell

RK-11056 - upgrade log4j core for log4shell mitigation

---

src/checkoutservice/Dockerfile
src/frontend/Dockerfile
src/productcatalogservice/Dockerfile
src/shippingservice/Dockerfile

RK-11495 - change goproxy jfrog order

---

src/emailservice/requirements.txt

see https://github.com/pallets/markupsafe/issues/286

RK-11635 - limit markupsafe due to breaking change

---

src/checkoutservice/go.mod
src/checkoutservice/go.sum
src/frontend/go.mod
src/frontend/go.sum
src/productcatalogservice/go.mod
src/productcatalogservice/go.sum
src/shippingservice/go.mod
src/shippingservice/go.sum

RK-11682 - Bump GoSDK version to 0.1.3

---

src/checkoutservice/Dockerfile
src/frontend/Dockerfile
src/productcatalogservice/Dockerfile
src/shippingservice/Dockerfile

Updated the gcflags for Go SDK deployments

RK-11706 - New gcflags GoSDK

---

src/emailservice/requirements.txt

RK-11847 - python-grpc git+https

---

src/recommendationservice/requirements.txt

This time I went over all the requirements files, should be ok now

RK-11848 - fix https requirements issue

---

src/emailservice/requirements.txt
src/recommendationservice/requirements.txt

RK-13711 - Add protobuf version pinning

---

src/checkoutservice/Dockerfile
src/frontend/Dockerfile
src/productcatalogservice/Dockerfile
src/shippingservice/Dockerfile

Use alternate build flags to allow go optimizations

RK-13820 - Allow golang build optimizations

---

.circleci/config.yml

RK-13951 - test

---

.circleci/config.yml

RK-14010 - fix argo deploy

---

.circleci/config.yml

RK-14056 - Helm deploy deprecation

---

.circleci/config.yml

RK-14215 - fix urls

---

.circleci/config.yml

RK-15716 - sandboxNodejs application templating fix

---

src/adservice/build.gradle

RK-17931 - jar-download-url

---

.circleci/config.yml

RK-20034 - fix-gitops-deploy

---

.circleci/config.yml

fix cloning master instead of staging

RK-20035 - gitops migration fix branch
